# Generated by Django 3.1.3 on 2021-07-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_remove_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='authorized',
            field=models.BooleanField(default=False, verbose_name='Se recibe confirmación para mensajería libre'),
        ),
        migrations.AddField(
            model_name='user',
            name='notificated',
            field=models.BooleanField(default=False, verbose_name='El usuario ha sido notificado'),
        ),
    ]
