# Generated by Django 3.1.3 on 2021-07-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_auto_20210728_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_join',
            field=models.BooleanField(default=False, verbose_name='El usuario ha autorizado recibir mensajes'),
        ),
        migrations.AlterField(
            model_name='user',
            name='authorized',
            field=models.BooleanField(default=False, verbose_name='Se recibe confirmación para mensajería libre/acepta términos'),
        ),
    ]
