# Generated by Django 3.1.3 on 2021-07-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_auto_20210729_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='notificated',
            new_name='notified',
        ),
    ]
