# Generated by Django 3.2.2 on 2021-08-03 15:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0007_auto_20210802_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notified',
        ),
        migrations.AlterField(
            model_name='user',
            name='authorization_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tiempo en que el usuario autoriza recibir mensajes'),
        ),
    ]
