# Generated by Django 3.2.9 on 2021-11-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_auto_20210803_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='no_session_message',
            field=models.BooleanField(default=False, verbose_name='Responder mensaje de no sesión'),
        ),
    ]
