# Generated by Django 3.2.9 on 2021-11-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_auto_20211112_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_time_block',
            new_name='last_time_write',
        ),
    ]
