# Generated by Django 3.2.9 on 2021-11-19 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_rename_last_time_block_user_last_time_write'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_join',
            field=models.BooleanField(default=True, verbose_name='El usuario ha autorizado recibir mensajes (firma documento)'),
        ),
    ]
