# Generated by Django 3.1.3 on 2021-07-28 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui', '0001_initial'),
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Especialista'),
        ),
        migrations.AddField(
            model_name='videos',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ui.entity', verbose_name='Entidad'),
        ),
    ]
