# Generated by Django 3.1.3 on 2021-07-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_auto_20210728_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='source_link',
            field=models.URLField(max_length=1024, verbose_name='Link del recurso'),
        ),
    ]
