# Generated by Django 3.1.3 on 2021-07-28 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant', '0006_auto_20210728_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description_message', models.TextField(max_length=1024, verbose_name='Descripción del mensaje')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='Paciente')),
                ('specialist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specialist', to=settings.AUTH_USER_MODEL, verbose_name='Especialista')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VirtualSessionVideos',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistant.virtualsession', verbose_name='Id mensaje asignado')),
                ('video', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistant.videos', verbose_name='Video de ejercicios asignado')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='whatsappmessagevideos',
            name='video',
        ),
        migrations.RemoveField(
            model_name='whatsappmessagevideos',
            name='whatsapp_message',
        ),
        migrations.DeleteModel(
            name='WhatsAppMessage',
        ),
        migrations.DeleteModel(
            name='WhatsAppMessageVideos',
        ),
    ]
