# Generated by Django 3.1.3 on 2021-07-28 21:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ui', '0002_remove_user_name'),
        ('assistant', '0007_auto_20210728_2104'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Videos',
            new_name='Video',
        ),
        migrations.RenameModel(
            old_name='VirtualSessionVideos',
            new_name='VirtualSessionVideo',
        ),
    ]
