# Generated by Django 3.1.3 on 2021-07-28 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0010_auto_20210728_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Titulo del video'),
        ),
        migrations.AlterField(
            model_name='virtualsession',
            name='description_message',
            field=models.TextField(blank=True, default='', max_length=1024, verbose_name='Descripción del mensaje'),
        ),
    ]
