# Generated by Django 3.1.3 on 2021-07-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0011_auto_20210728_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualsession',
            name='user_authorized',
            field=models.BooleanField(default=False, verbose_name='La sesión recibe confirmación del usuario'),
        ),
        migrations.AddField(
            model_name='virtualsession',
            name='user_notificated',
            field=models.BooleanField(default=False, verbose_name='La sesión notifica al usuario'),
        ),
        migrations.AlterField(
            model_name='virtualsession',
            name='description_message',
            field=models.TextField(blank=True, default='', max_length=1024, verbose_name='Mensaje de asistencia'),
        ),
    ]
