# Generated by Django 3.1.3 on 2021-07-30 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0013_virtualsession_first_join'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualsession',
            name='first_join',
        ),
        migrations.AlterField(
            model_name='virtualsession',
            name='user_authorized',
            field=models.BooleanField(default=False, verbose_name='Confirmación del usuario'),
        ),
        migrations.AlterField(
            model_name='virtualsession',
            name='user_notificated',
            field=models.BooleanField(default=False, verbose_name='Notificación al usuario'),
        ),
    ]
