# Generated by Django 3.1.3 on 2021-07-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0014_auto_20210730_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualsession',
            name='session_status',
            field=models.CharField(default='❌', max_length=256, verbose_name='Stado de la sesión'),
        ),
    ]
