# Generated by Django 3.1.3 on 2021-07-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0015_virtualsession_session_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualsession',
            name='session_status',
            field=models.CharField(default='La sesión ha sido programada.', max_length=256, verbose_name='Stado de la sesión'),
        ),
    ]
