# Generated by Django 3.1.3 on 2021-07-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0016_auto_20210730_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualsession',
            old_name='session_status',
            new_name='session_status_message',
        ),
        migrations.AddField(
            model_name='virtualsession',
            name='session_done',
            field=models.BooleanField(default=False, verbose_name='La sesión ha finalizado'),
        ),
    ]
