# Generated by Django 3.1.3 on 2021-07-30 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0017_auto_20210730_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualsession',
            old_name='user_notificated',
            new_name='user_notified',
        ),
    ]
