# Generated by Django 3.1.3 on 2021-08-03 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assistant', '0018_auto_20210730_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualsession',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL, verbose_name='Paciente'),
        ),
        migrations.AlterField(
            model_name='virtualsession',
            name='specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialist', to=settings.AUTH_USER_MODEL, verbose_name='Especialista'),
        ),
    ]
