# Generated by Django 3.2.2 on 2021-08-04 01:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0019_auto_20210802_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualsession',
            name='session_duration',
            field=models.IntegerField(default=60, verbose_name='Duración de la sesión en minutos'),
        ),
        migrations.CreateModel(
            name='VirtualSessionMessages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('message', models.CharField(max_length=256, verbose_name='Respuesta del paciente.')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assistant.virtualsession', verbose_name='Id de la sesión')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
