# Generated by Django 3.2.9 on 2021-11-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0020_auto_20210803_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualsession',
            name='commentary_messages_section',
            field=models.BooleanField(default=False, verbose_name='Indica cuando un usuario puede ingresar comentarios'),
        ),
    ]
