# Generated by Django 3.2.9 on 2021-11-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0021_virtualsession_commentary_messages_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualsession',
            name='is_session_expired',
            field=models.BooleanField(default=False, verbose_name='Bandera para determinar si una sesión expiró o no'),
        ),
    ]
