# Generated by Django 3.2.9 on 2021-11-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0023_auto_20211119_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualsession',
            name='session_items',
            field=models.TextField(blank=True, default='', max_length=1024, verbose_name='Elementos necesarios para le sesión'),
        ),
        migrations.AlterField(
            model_name='virtualsession',
            name='is_session_expired',
            field=models.BooleanField(default=False, verbose_name='Bandera para indicar si una sesión expiró o no'),
        ),
    ]
