# Generated by Django 3.2.9 on 2021-11-24 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0024_auto_20211119_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualsession',
            name='commentary_messages_section',
        ),
        migrations.AddField(
            model_name='virtualsession',
            name='last_commentary_message_section',
            field=models.BooleanField(default=False, verbose_name='Indica cuando un usuario puede ingresar comentario final'),
        ),
        migrations.AddField(
            model_name='virtualsession',
            name='user_presession_last_answer',
            field=models.DateTimeField(null=True, verbose_name='Fecha en la que se le responde al usuario despues de un comentario entre sesión'),
        ),
    ]
